### ISSUE TITLE
Find new redis host

### ISSUE THREAD

**Issue by jomo** [Jake0oo0/crafatar#49]
Our current redis host ([rediscloud for heroku](https://addons.heroku.com/rediscloud)) is limited to 25MB.
We can store approximately 100k keys with this (per day, due to heroku restarting once a day).

We have hit this limit 2 times already, causing Crafatar to crash:
```Log
2014-12-27 13:45:21.795895+00:00 app web.1 - -
2014-12-27 13:45:21.829964+00:00 app web.1 - - throw err;
2014-12-27 13:45:21.829972+00:00 app web.1 - - ^
2014-12-27 13:45:21.833744+00:00 app web.1 - - Error: OOM command not allowed when used memory > 'maxmemory'. at ReplyParser.<anonymous> (/app/node_modules/redis/index.js:317:31) at ReplyParser.emit (events.js:95:17) at ReplyParser.send_error (/app/node_modules/redis/lib/parser/javascript.js:296:10) at ReplyParser.execute (/app/node_modules/redis/lib/parser/javascript.js:181:22) at RedisClient.on_data (/app/node_modules/redis/index.js:547:27) Exception
2014-12-27 13:45:21.782351+00:00 app web.1 - - node_redis: no callback to send error: OOM command not allowed when used memory > 'maxmemory'.
2014-12-27 13:45:21.829499+00:00 app web.1 - - /app/node_modules/redis/index.js:582
2014-12-27 13:45:21.833758+00:00 app web.1 - -   at Socket.<anonymous> (/app/node_modules/redis/index.js:102:14)
2014-12-27 13:45:21.833760+00:00 app web.1 - -   at Socket.emit (events.js:95:17)
2014-12-27 13:45:21.833762+00:00 app web.1 - -   at Socket.<anonymous> (_stream_readable.js:764:14)
2014-12-27 13:45:21.833763+00:00 app web.1 - -   at Socket.emit (events.js:92:17)
2014-12-27 13:45:21.833765+00:00 app web.1 - -   at emitReadable_ (_stream_readable.js:426:10)
2014-12-27 13:45:22.827381+00:00 heroku web.1 - - Process exited with status 8
2014-12-27 13:45:22.836763+00:00 heroku web.1 - - State changed from up to crashed
```
Fortunately the error causes a crash and that causes heroku to restart, which also leads to flushing the database, resolving the problem on its own:
```Log
2014-12-27 13:45:22.837544+00:00 heroku web.1 - - State changed from crashed to starting
2014-12-27 13:45:24.936896+00:00 heroku web.1 - - Starting process with command `cp "modules/config.example.js" "modules/config.js" && node server.js`
2014-12-27 13:45:25.973146+00:00 app web.1 - - connecting to redis...
2014-12-27 13:45:26.057901+00:00 app web.1 - - Redis connection established.
2014-12-27 13:45:26.057953+00:00 app web.1 - - Running on heroku, flushing redis
2014-12-27 13:45:26.260774+00:00 heroku web.1 - - State changed from starting to up
```

While this problem somewhat fixes itself, it always means a couple of seconds downtime and ofc it deletes all our cached skins. It also leads to TooManyRequestsException.

**Comment by jomo** [comment]
Check out @c80eefd99292d5053d6a5ab44a1659b6b6e9a049 which should notice *before* redis fills up and then flushes it.
But our 25MB redis fills up within less than a day, so a larger one would be great. We've already been offered sponsored hosting and will probably get this set up soon.

However I agree that the long term solution is a different one, so [setting a TTL](http://www.redis.io/commands/expire) on keys might be the way to go.

Redis provides the `instantaneous_ops_per_sec` in its [info](http://www.redis.io/commands/info) command.

**Comment by connor4312** [comment]
I'd opt to just keep track of that in the app. Better to keep the rolling average over, say, 30 seconds than look at instantaneous ops, or you'll have expire times jumping around quite a bit.

**Comment by jomo** [comment]
Yes I would have used the ops per sec to calculate an average anyway.
Since redis only fills up when when we add keys to it we could figure an average write speed in the [save_hash](https://github.com/Jake0oo0/crafatar/blob/3a0a23e5b5995fdb5af5efa1328ebd54086cde2c/modules/cache.js#L99-L108) method.

Will think more about this when I'm back from work.
